### ISSUE TITLE
createTTG.py Code error

### ISSUE THREAD

**Issue by 464hee** [Henrik86/Topological-tumour-graphs#3]
**in createTTG.py  code  764-768:**                                 
if len(StromalNLymSmallDistanceCancer)==0:
    StromalNLymBSmallDistanceCancerAvg=np.NAN
else:
    StromalNLymSmallDistanceCancerAvg=np.mean(StromalNLymSmallDistanceCancer)
###

You should change StromalNLymBSmallDistanceCancerAvg to StromalNLymSmallDistanceCancerAvg on line 765 of the code

@Henrik86 @sathyam89

**Comment by Henrik86** [comment]
Thank you, I will have a look at it.

**Comment by 464hee** [comment]
> Thank you, I will have a look at it.

I would like to know how much time it takes for an H&E image to calculate the number of over a million cells(o+c+l) that you are calculating for these metrics. Because when I was calculating it, it took close to two days, and I don't know if you guys are also that time consuming.

**Comment by Henrik86** [comment]
Sorry for the delay in my reply. In order to be able to speed up the calculation(and in order to fit the graph into memory), we separated the tissue into subregions (tiles), calculated the graph measurements on these regions and aggregated them afterwards. We further merged cancer cells into single _cancer cluster nodes_ , which also reduced the graph size.
